configName: pic32mk_mcm_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024MCM100
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_le00_ls00;csp_apps_pic32cm_mc00;csp_apps_pic32cx_bz24_bz25;csp_apps_pic32mk;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_l21;csp_apps_sam_l22;gfx;motor_control;touch;validation;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.5.115\atdf\PIC32MK1024MCM100.atdf
