format_version: v1.0
type: UniqueComponent
attributes: {id: tmr1}
children:
- type: Symbols
  children:
  - type: Long
    attributes: {id: TIMER1_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '599'}
  - type: Float
    attributes: {id: TIMER1_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1092.2833'}
    - type: Values
      children:
      - type: User
        attributes: {value: '10.0'}
  - type: Combo
    attributes: {id: TIMER_UNIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: microsecond}
- type: ElementPosition
  attributes: {x: '500', y: '18', id: tmr1}
