files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 72A9E7D262DF08CF34B6213F85F35BD3
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 72A9E7D262DF08CF34B6213F85F35BD3
- generatedChecksum: 5B97621F771BBDD64DA1F5B81CB24C4F
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B97621F771BBDD64DA1F5B81CB24C4F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 240958B7D89740CACE01A6311D26890E
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\cdac
  name: plib_cdac1.c
  physicalPath: peripheral\cdac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 240958B7D89740CACE01A6311D26890E
- generatedChecksum: 06AD33CDAC3D9628D49C560FBDC77846
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 06AD33CDAC3D9628D49C560FBDC77846
- generatedChecksum: 39969C6CF19CD865A9C54E4A2FA96CCE
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39969C6CF19CD865A9C54E4A2FA96CCE
- generatedChecksum: 133F80597D933C56291833F8BC90B1BE
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 133F80597D933C56291833F8BC90B1BE
- generatedChecksum: 987D96C76FA16B31F8A49F32530D5969
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 987D96C76FA16B31F8A49F32530D5969
- generatedChecksum: 2B43DE7D2FB4CD5F1EEAF6ACF803462B
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\tmr1
  name: plib_tmr1.c
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2B43DE7D2FB4CD5F1EEAF6ACF803462B
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mk_mcj_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 49356E58BC48DBAE27AF5929151511CF
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 49356E58BC48DBAE27AF5929151511CF
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 685086098B2EA303F060F638C0BE1758
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\cdac
  name: plib_cdac1.h
  physicalPath: peripheral\cdac
  security: NON_SECURE
  type: HEADER
  userChecksum: 685086098B2EA303F060F638C0BE1758
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 9108AA0A33AAE0B38377112EE2F2AFC4
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: 9108AA0A33AAE0B38377112EE2F2AFC4
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: 05AE5FA71401B0C13CEDF4E47B913F34
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 05AE5FA71401B0C13CEDF4E47B913F34
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\tmr1
  name: plib_tmr1.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 64F8A910AD8A14AFE00172531F2C8F11
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 64F8A910AD8A14AFE00172531F2C8F11
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
