files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 3165F08CF1D6D628879C131D1753341E
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3165F08CF1D6D628879C131D1753341E
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F78BA15ADFEB010B572368BBCD0F61F0
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F78BA15ADFEB010B572368BBCD0F61F0
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 50F0C023B768DC617E111F3A73567833
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 50F0C023B768DC617E111F3A73567833
- generatedChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\icap
  name: plib_icap1.c
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
- generatedChecksum: 1A6F78907CA4300156425C1382FAFAA7
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1A6F78907CA4300156425C1382FAFAA7
- generatedChecksum: DFE5ECCCE683DA03A2A94AA1183AEABD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: DFE5ECCCE683DA03A2A94AA1183AEABD
- generatedChecksum: 171F05807BE1DA35533DFD415B32C57E
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 171F05807BE1DA35533DFD415B32C57E
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config\pic32mk_mcm_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEAD678D52A900BF13F45EFDA811BC10
- generatedChecksum: 5FD68B70572074C50D88658E36489B87
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FD68B70572074C50D88658E36489B87
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
- generatedChecksum: C735FE07D839BEF0340E5DD22C2DCC74
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\icap
  name: plib_icap1.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: C735FE07D839BEF0340E5DD22C2DCC74
- generatedChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\icap
  name: plib_icap_common.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
- generatedChecksum: E30FFC13DBD9F668569DE45E56387DCD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: E30FFC13DBD9F668569DE45E56387DCD
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 9DF2058BBA7397756E0CED63F294C4C3
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DF2058BBA7397756E0CED63F294C4C3
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 51008F94CB120E2E6113CD8B5B91734A
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 51008F94CB120E2E6113CD8B5B91734A
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
