configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32cm_jh00_jh01;core_apps_sam_g55;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_ef;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_g55;csp_apps_sam_ha1;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.4.117\atdf\PIC32MK1024GPE100.atdf
