files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 2D30B6411D6383F55D5FD4281232D96F
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2D30B6411D6383F55D5FD4281232D96F
- generatedChecksum: 172B02348EE03CCF7EAE82775187E2E5
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 172B02348EE03CCF7EAE82775187E2E5
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mcj.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: BDA2E207C9A4217DE1FABDDB2987D7AD
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: BDA2E207C9A4217DE1FABDDB2987D7AD
- generatedChecksum: B4D484C3EBFF7D6F68C22C87DD9D7504
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4D484C3EBFF7D6F68C22C87DD9D7504
- generatedChecksum: 83BB3057E3406368438EDF2C8E7DDAC7
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BB3057E3406368438EDF2C8E7DDAC7
- generatedChecksum: 7CD1EDDF64BB45965E2652000C1FBFF5
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\nvm
  name: plib_nvm.c
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CD1EDDF64BB45965E2652000C1FBFF5
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mk_mcj_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 60A4F6B165D223C8349FCA24650494B8
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 60A4F6B165D223C8349FCA24650494B8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: D447CD4001E1894778E5FF74450159B2
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D447CD4001E1894778E5FF74450159B2
- generatedChecksum: 629A0B8A7FAFE98404C974D0AAFA5EB1
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\nvm
  name: plib_nvm.h
  physicalPath: peripheral\nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: 629A0B8A7FAFE98404C974D0AAFA5EB1
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 837FF87C9FE153E73D01A0A76EEA535E
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 837FF87C9FE153E73D01A0A76EEA535E
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
