files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: FDEF2876AEF42125BD7D43A8EB84B7F6
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FDEF2876AEF42125BD7D43A8EB84B7F6
- generatedChecksum: 61853226EDE429F6AE2086DC844B1D95
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 61853226EDE429F6AE2086DC844B1D95
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mcm.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C555A442CDFB937455882EFF5365B7B0
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\adchs
  name: plib_adchs.c
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: C555A442CDFB937455882EFF5365B7B0
- generatedChecksum: F562AC1A42305B50955E28F1CAD50CFD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: F562AC1A42305B50955E28F1CAD50CFD
- generatedChecksum: 4605FC43F7E880A5A365341E03979053
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4605FC43F7E880A5A365341E03979053
- generatedChecksum: C04A08E02591FD3CA18F2CA1EC25B8A2
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C04A08E02591FD3CA18F2CA1EC25B8A2
- generatedChecksum: 7FFDBC99E5FEE8A22D8797FCB1249D5E
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr3.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7FFDBC99E5FEE8A22D8797FCB1249D5E
- generatedChecksum: 171F05807BE1DA35533DFD415B32C57E
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 171F05807BE1DA35533DFD415B32C57E
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config\pic32mk_mcm_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEAD678D52A900BF13F45EFDA811BC10
- generatedChecksum: 3E46EBAF5DE1134F4A7ACBBF556CA5CC
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 3E46EBAF5DE1134F4A7ACBBF556CA5CC
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 74058744638925EEB20F58B4328F1B68
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\adchs
  name: plib_adchs.h
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 74058744638925EEB20F58B4328F1B68
- generatedChecksum: 5485BB926F2ECC7BD1D7B2DE51ED2795
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\adchs
  name: plib_adchs_common.h
  physicalPath: peripheral\adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 5485BB926F2ECC7BD1D7B2DE51ED2795
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
- generatedChecksum: AB441E032FD7B269DB6B2AA5661A890C
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr3.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: AB441E032FD7B269DB6B2AA5661A890C
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 51008F94CB120E2E6113CD8B5B91734A
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 51008F94CB120E2E6113CD8B5B91734A
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
