format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '16'}
- type: ElementPosition
  attributes: {x: '30', y: '59', id: tmr2}
