files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: E7D59A635288D5D9C49B01510ACD9377
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E7D59A635288D5D9C49B01510ACD9377
- generatedChecksum: 0FB93F7461AA26C1FDB0D873DCE43831
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0FB93F7461AA26C1FDB0D873DCE43831
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mca.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 4E559808316A6DDE3AA847E64D8EBDDF
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4E559808316A6DDE3AA847E64D8EBDDF
- generatedChecksum: 41D5542450D9F8E865B5CB4EFC002BA5
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 41D5542450D9F8E865B5CB4EFC002BA5
- generatedChecksum: C3F81546F6C6DEFB8B9CD83553BA9131
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C3F81546F6C6DEFB8B9CD83553BA9131
- generatedChecksum: 69E12FECBE818851E9A74F3C614EEC8C
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/i2c/master
  name: plib_i2c2_master.c
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 69E12FECBE818851E9A74F3C614EEC8C
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_mca_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 37D853AB85710FC8D34453BF9E6DA9B5
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 37D853AB85710FC8D34453BF9E6DA9B5
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: B5377459A947965D398E898B7BECC090
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: B5377459A947965D398E898B7BECC090
- generatedChecksum: E5698A26DEE4F0D6DCFBD59AA2F80175
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: E5698A26DEE4F0D6DCFBD59AA2F80175
- generatedChecksum: 98DDD931F1A3452F1369FD2708D64EEA
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/i2c/master
  name: plib_i2c2_master.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: 98DDD931F1A3452F1369FD2708D64EEA
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/i2c/master
  name: plib_i2c_master_common.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: AFEEF05303BA1755340AEA0C8E51A3C5
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: p32MK0128MCA048.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: AFEEF05303BA1755340AEA0C8E51A3C5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
