files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 642BDB5E5F84C67DBF4759865DF20876
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 642BDB5E5F84C67DBF4759865DF20876
- generatedChecksum: 06C5CE7DA5389AA0AF7DDF0F4F8A7FCD
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 06C5CE7DA5389AA0AF7DDF0F4F8A7FCD
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3BE90ADA7BFDD68C0B067C1C756D062B
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BE90ADA7BFDD68C0B067C1C756D062B
- generatedChecksum: DC456BD30134E9EAD63388D1600DEF1E
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC456BD30134E9EAD63388D1600DEF1E
- generatedChecksum: 987D96C76FA16B31F8A49F32530D5969
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 987D96C76FA16B31F8A49F32530D5969
- generatedChecksum: B54DB26E37D8D2A8CB63E13AD588BA40
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm.c
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: SOURCE
  userChecksum: B54DB26E37D8D2A8CB63E13AD588BA40
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 765DB808515907D0834DE9706A46D4FF
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 765DB808515907D0834DE9706A46D4FF
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: F842AB8F49E36AE56AEB45606D25E0F6
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F842AB8F49E36AE56AEB45606D25E0F6
- generatedChecksum: 12CBE2439F4C4DECD2B376033BBADA45
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 12CBE2439F4C4DECD2B376033BBADA45
- generatedChecksum: 212B045963C5C25F90BB73C34E2DE264
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/mcpwm
  name: plib_mcpwm_common.h
  physicalPath: peripheral/mcpwm
  security: NON_SECURE
  type: HEADER
  userChecksum: 212B045963C5C25F90BB73C34E2DE264
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 4BD241A94AC776C7B963BF3833BD07DB
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 4BD241A94AC776C7B963BF3833BD07DB
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
