files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 3C7A0DA4911B96A9084670E5B060F439
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3C7A0DA4911B96A9084670E5B060F439
- generatedChecksum: 81C1AC6EBBBAD107F42A666611DAC56C
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 81C1AC6EBBBAD107F42A666611DAC56C
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_gp_db.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A2CC1D164E348221FF471BF9DA3A4C0C
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2CC1D164E348221FF471BF9DA3A4C0C
- generatedChecksum: 2F7520CDD61370BFE0CCB226D0367D96
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F7520CDD61370BFE0CCB226D0367D96
- generatedChecksum: 7C0830881A206FCEDB0683E6D86149C0
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7C0830881A206FCEDB0683E6D86149C0
- generatedChecksum: DF9BC4CBEB9C001FF4192D7647A222F7
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi6_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF9BC4CBEB9C001FF4192D7647A222F7
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_mcm_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 620874D0AC7EE7C56441422DEA4DE593
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 620874D0AC7EE7C56441422DEA4DE593
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: DCBDFFF234ECE93C3216BCF0B5708191
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: DCBDFFF234ECE93C3216BCF0B5708191
- generatedChecksum: 0C75166C5BE75E8E7408EC9C421BDBF7
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi6_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 0C75166C5BE75E8E7408EC9C421BDBF7
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 076A5CDEAE185EDCB946BAC9F1AD03E5
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 076A5CDEAE185EDCB946BAC9F1AD03E5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
