files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: F725F87346ED9E098AD7C3BE75EF766A
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F725F87346ED9E098AD7C3BE75EF766A
- generatedChecksum: F2AF1D831A4174B30518C37BC185C016
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F2AF1D831A4174B30518C37BC185C016
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mcj.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 0CB2D9F17CE7194CB73F1842BE843E56
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\canfd
  name: plib_canfd1.c
  physicalPath: peripheral\canfd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB2D9F17CE7194CB73F1842BE843E56
- generatedChecksum: C22B4B37FCD229A7336B5600B2B429B3
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: C22B4B37FCD229A7336B5600B2B429B3
- generatedChecksum: CD32F84EC6EFC97A67BF492E00396986
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD32F84EC6EFC97A67BF492E00396986
- generatedChecksum: 244386545902CD1FAAF7D12B3DBF139B
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 244386545902CD1FAAF7D12B3DBF139B
- generatedChecksum: B2127FC46CD72C03043ABEE407F3C16C
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2127FC46CD72C03043ABEE407F3C16C
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config\pic32mk_mcj_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: B9364476D04B41EE8ACB5E6B4B0FCA9A
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B9364476D04B41EE8ACB5E6B4B0FCA9A
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\canfd
  name: plib_canfd1.h
  physicalPath: peripheral\canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
- generatedChecksum: AEFE39C8E52415FE642815364C699E0C
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\canfd
  name: plib_canfd_common.h
  physicalPath: peripheral\canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AEFE39C8E52415FE642815364C699E0C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: AD291C125098707A1495AB505177548F
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: AD291C125098707A1495AB505177548F
- generatedChecksum: 38A7F5DCE6FE0F7B9E02AA5446AC3B68
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 38A7F5DCE6FE0F7B9E02AA5446AC3B68
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mk_mcj_curiosity_pro\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: BF93AF2E2FCE1A16EFE45E0F51AC34C3
  logicalPath: config\pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: BF93AF2E2FCE1A16EFE45E0F51AC34C3
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
