format_version: v1.0
type: UniqueComponent
attributes: {id: adchs}
children:
- type: Symbols
  children:
  - type: Long
    attributes: {id: ADC0TIME__ADCDIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADC0TIME__BCHEN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Long
    attributes: {id: ADC0TIME__SAMC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC0TIME__SELRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCDSTAT__RAFIEN0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCDSTAT__RBFIEN0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCGIRQEN1__AGIEN0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ADCHS_0_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: ADCHS_0_NAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '6291456'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '131073'}
  - type: Hex
    attributes: {id: ADCHS_ADCCSS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCCSS2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCDSTAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCGIRQEN1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1'}
  - type: Hex
    attributes: {id: ADCHS_ADCIMCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTIME1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '50397185'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '6'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRGMODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '196608'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1875.0001'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1875.0001'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1764.7059'}
  - type: String
    attributes: {id: ADCHS_DMA_STATUS_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCDSTAT}
  - type: Hex
    attributes: {id: ADCHS_IEC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1024'}
  - type: Boolean
    attributes: {id: ADCHS_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Float
    attributes: {id: ADCHS_TADC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33.333332'}
  - type: Float
    attributes: {id: ADCHS_TADC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33.333332'}
  - type: Float
    attributes: {id: ADCHS_TADC7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33.333332'}
  - type: Float
    attributes: {id: ADCHS_TCLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '8.333333'}
  - type: Float
    attributes: {id: ADCHS_TQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '16.666666'}
  - type: Boolean
    attributes: {id: ADCIMCON1__DIFF0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCIMCON1__SIGN0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG1__TRGSRC0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: KeyValueSet
    attributes: {id: ADCTRGMODE__SH0ALT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CallbackRegister}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH4}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH15}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH10}
  - type: Boolean
    attributes: {id: ADC_DMA_ENABLED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'false'}
  - type: Boolean
    attributes: {id: ADC_DMA_INT_ENABLED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'false'}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultGet}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultIsReady}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelConversionStart}
  - type: Boolean
    attributes: {id: AN0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: INT_SOURCE_ADC_DATA0}
- type: ElementPosition
  attributes: {x: '345', y: '22', id: adchs}
