format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '120'}
  - type: KeyValueSet
    attributes: {id: TIMER_32BIT_MODE_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '234375'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '4294967295'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '234374'}
  - type: KeyValueSet
    attributes: {id: TIMER_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1.8325194E7'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1000.0'}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '32'}
  - type: String
    attributes: {id: TMR_IEC_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IEC0}
  - type: String
    attributes: {id: TMR_IFS_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IFS0}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '256'}
- type: ElementPosition
  attributes: {x: '33', y: '77', id: tmr2}
