format_version: v1.0
type: UniqueComponent
attributes: {id: cdac1}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CDAC_DACOE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: CDAC_REFSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '340', y: '17', id: cdac1}
