files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 9CF951E6D003F0282CB4DD26B2E7BB5C
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9CF951E6D003F0282CB4DD26B2E7BB5C
- generatedChecksum: C609F95F5E02AA97C19EC480AC551C75
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C609F95F5E02AA97C19EC480AC551C75
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 387103412B29FC5DEB406DC63BCCB7BD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: 387103412B29FC5DEB406DC63BCCB7BD
- generatedChecksum: 12142F6A49DF3DE119567A45A997BE32
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 12142F6A49DF3DE119567A45A997BE32
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: FD0DC1E406C11FFD22F1218B17FB1BB4
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD0DC1E406C11FFD22F1218B17FB1BB4
- generatedChecksum: D8C0DFBBB505EEC4C1B5788F06BF9485
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: D8C0DFBBB505EEC4C1B5788F06BF9485
- generatedChecksum: 804B8A42CE59B3E52424F7CB8BDF21F7
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/tmr
  name: plib_tmr3.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 804B8A42CE59B3E52424F7CB8BDF21F7
- generatedChecksum: 8455F0B5875D973A5BFAF295A84E6DC4
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8455F0B5875D973A5BFAF295A84E6DC4
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: 143683D0529E03A9889733ABEDF16D7E
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 143683D0529E03A9889733ABEDF16D7E
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: FEE2978FD8010F2C06819054DF0056F0
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: FEE2978FD8010F2C06819054DF0056F0
- generatedChecksum: 09351FBE7294FA0B2256E194A70F04A1
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: 09351FBE7294FA0B2256E194A70F04A1
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: E117D25137D333D9E62C091362100BB0
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: E117D25137D333D9E62C091362100BB0
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: F842AB8F49E36AE56AEB45606D25E0F6
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F842AB8F49E36AE56AEB45606D25E0F6
- generatedChecksum: AB441E032FD7B269DB6B2AA5661A890C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/tmr
  name: plib_tmr3.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: AB441E032FD7B269DB6B2AA5661A890C
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 442A504503193FF627F7C0952797B7BD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 442A504503193FF627F7C0952797B7BD
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 4BD241A94AC776C7B963BF3833BD07DB
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 4BD241A94AC776C7B963BF3833BD07DB
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
