configName: pic32mk_mca_curiosity_pro
folderName: pic32mk_mca_curiosity_pro
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\h3
processor: PIC32MK0128MCA048
projectName: spi_self_loopback_interrupt_pic32mk_mca_curiosity_pro
settings:
  PackageFilter: bootloader;bsp;core;crypto;crypto_apps_encrypt_decrypt;csp;dev_packs;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\0.1.28\atdf\PIC32MK0128MCA048.atdf
