configName: pic32mk_mcj_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK0512MCJ064
projectName: adchs_interrupt_pic32mk_mcj_curiosity_pro
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;micrium_ucos3;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.4.94\atdf\PIC32MK0512MCJ064.atdf
