files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 87A488F5C7A1A2FF1A829F1007A0B094
  logicalPath: config/pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 87A488F5C7A1A2FF1A829F1007A0B094
- generatedChecksum: A8985D6495847E1833F4095F48BDB612
  logicalPath: config/pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A8985D6495847E1833F4095F48BDB612
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: EA22B00D66EBA6BCA1F735BE6102F33F
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: EA22B00D66EBA6BCA1F735BE6102F33F
- generatedChecksum: E1799A0DD5368E13D4D99AF37A9B60C0
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: E1799A0DD5368E13D4D99AF37A9B60C0
- generatedChecksum: C96B87F10BB9EFFAEAAEBDFFD63ADC9F
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C96B87F10BB9EFFAEAAEBDFFD63ADC9F
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mk_gp_db/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 360B57F4E6E8EF6B4BF89CD59C3B27E8
  logicalPath: config/pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 360B57F4E6E8EF6B4BF89CD59C3B27E8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_gp_db
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F666CF132ECA91F43C2A25389BA2AC28
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F666CF132ECA91F43C2A25389BA2AC28
- generatedChecksum: C64C129731EBD0435F544C790BCA44F9
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: C64C129731EBD0435F544C790BCA44F9
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: BC41C20C45D02ADFBD17AC9120F7A943
  logicalPath: config/pic32mk_gp_db
  name: p32MK1024GPE100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: BC41C20C45D02ADFBD17AC9120F7A943
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
