files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: C28D62D971F2530C093901CB1DA5E75D
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C28D62D971F2530C093901CB1DA5E75D
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mk_mca.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D5B8E9DCD652601A45B7C3C4B15D913E
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: D5B8E9DCD652601A45B7C3C4B15D913E
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: F13192668E35956357830F85E7807B61
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: F13192668E35956357830F85E7807B61
- generatedChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E74E8218E54427BDBAE8B4238D55E4C
- generatedChecksum: D2B5BDC2F4578FDBBADED01931AF6259
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/wdt
  name: plib_wdt.c
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: D2B5BDC2F4578FDBBADED01931AF6259
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config/pic32mk_mca_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: D67902EF0C032A05DB4B325A1799F252
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D67902EF0C032A05DB4B325A1799F252
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: AF7742F518C17F367FA8497AF749E07B
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: AF7742F518C17F367FA8497AF749E07B
- generatedChecksum: B5377459A947965D398E898B7BECC090
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: B5377459A947965D398E898B7BECC090
- generatedChecksum: A9558B36DDFE7A804B763A1532EFB967
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: A9558B36DDFE7A804B763A1532EFB967
- generatedChecksum: 687F99E456839E29578ACB606A2A0083
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 687F99E456839E29578ACB606A2A0083
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 52646F9F1734C5AA98A212549F6FE3E3
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/wdt
  name: plib_wdt.h
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: 52646F9F1734C5AA98A212549F6FE3E3
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: F1A1EA465155CE2050076005C47E467B
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: p32MK0128MCA048.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: F1A1EA465155CE2050076005C47E467B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
